
dist: xenial
language: python
python:
  - "3.6"
install:
  - pip install pipenv
  - pipenv install --dev 
  - pipenv install codecov
script:
  - python3 -m pytest --cov=last_shout tests/
after_success:
  - codecov